#!/bin/bash

# Script to handle commits to github repository

git add $1
echo $1

if(($?>0))
then
	echo "Cannot make commit"
	exit
fi

echo -n "Enter commit message: "
read msg

if (($? > 0))
then
	echo "Did not commit"
	exit
fi

